create table if not exists public.tentativas_acesso (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('login', 'recuperacao')),
  chave_hash text not null check (chave_hash ~ '^[0-9a-f]{64}$'),
  ip_hash text not null check (ip_hash ~ '^[0-9a-f]{64}$'),
  permitido boolean not null,
  sucesso boolean,
  usuario_id uuid references public.usuarios(id) on delete set null,
  criado_em timestamptz not null default now(),
  finalizado_em timestamptz
);

alter table public.tentativas_acesso enable row level security;

create index if not exists tentativas_acesso_chave_idx
  on public.tentativas_acesso (tipo, chave_hash, criado_em desc);

create index if not exists tentativas_acesso_ip_idx
  on public.tentativas_acesso (tipo, ip_hash, criado_em desc);

create or replace function public.registrar_tentativa_acesso_v1(
  p_tipo text,
  p_chave_hash text,
  p_ip_hash text
)
returns table(tentativa_id bigint, permitido boolean, tentar_novamente_em integer)
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
as $$
declare
  v_janela interval;
  v_limite_chave integer;
  v_limite_ip integer;
  v_qtd_chave integer;
  v_qtd_ip integer;
  v_permitido boolean;
  v_retry integer;
  v_id bigint;
begin
  if p_tipo not in ('login', 'recuperacao') then
    raise exception using message = 'Tipo de tentativa inválido.', errcode = '22023';
  end if;

  if p_chave_hash is null or p_chave_hash !~ '^[0-9a-f]{64}$'
     or p_ip_hash is null or p_ip_hash !~ '^[0-9a-f]{64}$' then
    raise exception using message = 'Identificadores de segurança inválidos.', errcode = '22023';
  end if;

  if p_tipo = 'login' then
    v_janela := interval '15 minutes';
    v_limite_chave := 10;
    v_limite_ip := 30;
    v_retry := 900;
  else
    v_janela := interval '30 minutes';
    v_limite_chave := 3;
    v_limite_ip := 10;
    v_retry := 1800;
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended('tentativa-acesso:' || p_tipo || ':' || p_ip_hash || ':' || p_chave_hash, 0)
  );

  delete from public.tentativas_acesso
  where criado_em < pg_catalog.now() - interval '90 days';

  select count(*) into v_qtd_chave
  from public.tentativas_acesso
  where tipo = p_tipo
    and chave_hash = p_chave_hash
    and criado_em >= pg_catalog.now() - v_janela;

  select count(*) into v_qtd_ip
  from public.tentativas_acesso
  where tipo = p_tipo
    and ip_hash = p_ip_hash
    and criado_em >= pg_catalog.now() - v_janela;

  v_permitido := v_qtd_chave < v_limite_chave and v_qtd_ip < v_limite_ip;

  insert into public.tentativas_acesso(tipo, chave_hash, ip_hash, permitido)
  values (p_tipo, p_chave_hash, p_ip_hash, v_permitido)
  returning id into v_id;

  return query select v_id, v_permitido, case when v_permitido then 0 else v_retry end;
end;
$$;

create or replace function public.finalizar_tentativa_acesso_v1(
  p_tentativa_id bigint,
  p_sucesso boolean,
  p_usuario_id uuid default null
)
returns boolean
language plpgsql
security definer
set search_path to 'pg_catalog', 'public'
as $$
begin
  update public.tentativas_acesso
  set sucesso = coalesce(p_sucesso, false),
      usuario_id = p_usuario_id,
      finalizado_em = pg_catalog.now()
  where id = p_tentativa_id
    and finalizado_em is null;

  return found;
end;
$$;

revoke all on table public.tentativas_acesso from public, anon, authenticated;
revoke all on sequence public.tentativas_acesso_id_seq from public, anon, authenticated;

revoke all on function public.registrar_tentativa_acesso_v1(text,text,text) from public, anon, authenticated;
grant execute on function public.registrar_tentativa_acesso_v1(text,text,text) to service_role;

revoke all on function public.finalizar_tentativa_acesso_v1(bigint,boolean,uuid) from public, anon, authenticated;
grant execute on function public.finalizar_tentativa_acesso_v1(bigint,boolean,uuid) to service_role;